name: Python Build, Run, and Test
run-name: Build - Run - Test

on:
  - pull_request

permissions:
  contents: read

jobs:
  setup_build_run:
    runs-on: [self-hosted, linux, x64]
    container: 
      image: python:latest
      env:
        TERM: xterm-256color
      volumes: 
        - /home/ryan_urq/playlistCSVConverterApp/.cache:/toMove/.cache
        - /home/ryan_urq/playlistCSVConverterApp/appSettings.json:/toMove/appSettings.json
        - /export/NAS/Music/:/export/NAS/Music/
        - /export/NAS/Playlists/:/export/NAS/Playlists/
        - /home/ryan_urq/playlistCSVConverterApp/playlists/:/toMove/playlists/
    steps:
    - uses: actions/checkout@v4

    - name: Prepare container
      run: |
        git config --global --add safe.directory '*'
        cp -r /toMove/* ./

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run app
      run: |
        if [ -f ./main.py -a ./.cache -a -f ./appSettings.json ]; then python ./main.py -aq; 
        else echo "App ended with error code $?"; fi

    - name: Test with pytest
      run: |
        pytest
